site_name: scotch
theme: readthedocs
repo_url: https://github.com/qcaudron/scotch/
site_description: Markov Chains in Python
use_directory_urls: true

pages:
- ["index.md", "scotch"]
- ["quick-start/index.md", "Quick-Start", "Quick-Start : The SIR model"]
- ["examples/random_walk.md", "Examples", "Whisky-Fuelled Random Walker"]
- ["examples/lotka_volterra.md", "Examples", "Lotka-Volterra"]
