site_name: scotch
theme: readthedocs
repo_url: https://github.com/qcaudron/scotch/
site_description: Markov Chains in Python
use_directory_urls: true

pages:
- ["index.md", "scotch"]
- ["scotch/quickstart.md", "scotch", "Quick Start"]
- ["scotch/scotch_models.md", "scotch", "Describing scotch models"]
- ["scotch/simulation_algorithms.md", "scotch", "Simulation"]
- ["markov_processes/ctmc.md", "Markov Chains", "Continuous-time Markov Chains"]
- ["markov_processes/algorithms.md", "Markov Chains", "Simulation algorithms"]
- ["examples/random_walk.md", "Examples", "1. Whisky-Fuelled Random Walk"]
- ["examples/lotka_volterra.md", "Examples", "2. Lotka-Volterra Equations"]
- ["examples/seir.md", "Examples", "3. SEIR Epidemic Model"]
