site_name: scotch
theme: cosmo

pages:
- ["index.md", "scotch"]
- ["markov_processes/ctmc.md", "Markov Chains", "Continuous-time Markov Chains"]
- ["scotch/scotch_models.md", "scotch", "scotch Model Description"]
- ["scotch/simulation_algorithms.md", "scotch", "Simulation Algorithms"]
- ["examples/random_walk.md", "Examples", "1. Whisky-Fuelled Random Walk"]
- ["examples/lotka_volterra.md", "Examples", "2. Lotka-Volterra Equations"]
- ["examples/seir.md", "Examples", "3. SEIR Epidemic Model"]
